// <auto-generated />
using System;
using DP_BurLida.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DP_BurLida.Migrations
{
    [DbContext(typeof(ByrlidaContext))]
    [Migration("20260312072234_AddDeviceTokenTable")]
    partial class AddDeviceTokenTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DP_BurLida.Data.ModelsData.BrigadeModelData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DrillingMasterAssistant")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Driver")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NameBrigade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("int");

                    b.Property<string>("Technic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ResponsibleUserId");

                    b.ToTable("BrigadeModelData", (string)null);
                });

            modelBuilder.Entity("DP_BurLida.Data.ModelsData.DeviceTokenModelData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserEmail", "Platform");

                    b.ToTable("DeviceToken", (string)null);
                });

            modelBuilder.Entity("DP_BurLida.Data.ModelsData.NotificationModelData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("RecipientEmail", "IsRead");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("DP_BurLida.Data.ModelsData.OrderCommentModelData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("DoneAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDone")
                        .HasColumnType("bit");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderComment", (string)null);
                });

            modelBuilder.Entity("DP_BurLida.Data.ModelsData.OrderInstallmentPaymentStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SlotKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId", "SlotKey")
                        .IsUnique();

                    b.ToTable("OrderInstallmentPaymentStatus", (string)null);
                });

            modelBuilder.Entity("DP_BurLida.Data.ModelsData.OrderModelData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Arrangement")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ArrangementBrigadeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ArrangementDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ArrangementDone")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("ArrangementFirstContribution")
                        .HasColumnType("int");

                    b.Property<int?>("ArrangementFirstPayment")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ArrangementFirstPaymentDueDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ArrangementFourthPayment")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ArrangementFourthPaymentDueDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ArrangementSecondPayment")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ArrangementSecondPaymentDueDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ArrangementThirdPayment")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ArrangementThirdPaymentDueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BrigadeStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Contractor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Coordinates")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreationTimeData")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Depth")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Diameter")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("DrillingBrigadeId")
                        .HasColumnType("int");

                    b.Property<int?>("DrillingFirstContribution")
                        .HasColumnType("int");

                    b.Property<int?>("DrillingFirstPayment")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DrillingFirstPaymentDueDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DrillingFourthPayment")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DrillingFourthPaymentDueDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DrillingSecondPayment")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DrillingSecondPaymentDueDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DrillingThirdPayment")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DrillingThirdPaymentDueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DynamicLevel")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Filter")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("InstallmentEripNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsArrangementInstallment")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDrillingInstallment")
                        .HasColumnType("bit");

                    b.Property<int?>("MetersCount")
                        .HasColumnType("int");

                    b.Property<string>("NameClient")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<int>("PricePerMeter")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<int>("Pump")
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    b.Property<string>("PumpInstalled")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PumpModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sewer")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("StaticLevel")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurnameClient")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TotalArrangementAmount")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TotalDrillingAmount")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("WorkDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ArrangementBrigadeId");

                    b.HasIndex("DrillingBrigadeId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("DP_BurLida.Data.ModelsData.SkladModelData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameSubjecte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SkladModelData");
                });

            modelBuilder.Entity("DP_BurLida.Data.ModelsData.UserModelData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserModelData");
                });

            modelBuilder.Entity("DP_BurLida.Data.ModelsData.BrigadeModelData", b =>
                {
                    b.HasOne("DP_BurLida.Data.ModelsData.UserModelData", "ResponsibleUser")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ResponsibleUser");
                });

            modelBuilder.Entity("DP_BurLida.Data.ModelsData.OrderCommentModelData", b =>
                {
                    b.HasOne("DP_BurLida.Data.ModelsData.OrderModelData", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DP_BurLida.Data.ModelsData.OrderModelData", b =>
                {
                    b.HasOne("DP_BurLida.Data.ModelsData.BrigadeModelData", "ArrangementBrigade")
                        .WithMany()
                        .HasForeignKey("ArrangementBrigadeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DP_BurLida.Data.ModelsData.BrigadeModelData", "DrillingBrigade")
                        .WithMany()
                        .HasForeignKey("DrillingBrigadeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ArrangementBrigade");

                    b.Navigation("DrillingBrigade");
                });
#pragma warning restore 612, 618
        }
    }
}
